## Importação e Carregamento dos Dados

Importação da biblioteca Pandas e carregamento do dataset para realização da análise inicial da estrutura e tipagem dos dados.

In [3]:
import pandas as pd
df = pd.read_csv("../data/spotify.csv")
df.head()

,user_id,country,age,signup_date,subscription_type,subscription_status,months_inactive,inactive_3_months_flag,ad_interaction,ad_conversion_to_subscription,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,favorite_genre,most_liked_feature,desired_future_feature,primary_device,playlists_created,avg_skips_per_day
0,1,France,25,2021-08-19,Premium Duo,Active,0,0,No,No,4,10.13,Bollywood,Radio,Concert Alerts,Tablet,7,8
1,2,Indonesia,20,2022-06-06,Premium Family,Active,0,0,Yes,No,5,11.63,Latin,Podcasts,Lyrics Translation,Mobile,7,6
2,3,Italy,53,2024-01-04,Premium Individual,Active,0,0,Yes,Yes,3,9.50,Bollywood,Lyrics,Better AI Recommendations,Desktop,6,5
3,4,Italy,48,2018-08-26,Premium Individual,Active,1,0,No,No,4,13.16,Electronic,Playlists,Social Listening,Smart Speaker,11,8
4,5,Australia,18,2020-05-29,Free,Active,0,0,No,No,4,12.70,Indie,Daily Mix,Lyrics Translation,Tablet,10,11

## Verificação da Estrutura do Dataset

Análise da dimensionalidade do dataset para validação da quantidade de registros e atributos disponíveis. Foram identificadas 18 colunas e 50.000 linhas.

In [ ]:
df.shape

(50000, 18)

## Validação da Estrutura e Tipagem dos Dados

Análise das informações estruturais do dataset utilizando `df.info()` para verificação da tipagem das colunas, quantidade de registros não nulos e consistência dos dados.

Foi identificado que o dataset não possui valores nulos, considerando que todas as colunas apresentaram a mesma quantidade de valores não nulos em relação ao total de registros.

Também foi verificado que a coluna `signup_date` estava definida como string, sendo necessária a conversão para o tipo datetime para adequação das análises temporais.

Além disso, a coluna `inactive_3_months_flag` foi identificada como inteiro (`int64`), embora sua definição no dataset represente um valor booleano, exigindo a conversão para o tipo `bool`.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   user_id                         50000 non-null  int64
 1   country                         50000 non-null  str
 2   age                             50000 non-null  int64
 3   signup_date                     50000 non-null  str
 4   subscription_type               50000 non-null  str
 5   subscription_status             50000 non-null  str
 6   months_inactive                 50000 non-null  int64
 7   inactive_3_months_flag          50000 non-null  int64
 8   ad_interaction                  50000 non-null  str
 9   ad_conversion_to_subscription   50000 non-null  str
 10  music_suggestion_rating_1_to_5  50000 non-null  int64
 11  avg_listening_hours_per_week    50000 non-null  float64
 12  favorite_genre                  50000 non-null  str
 13  most_liked_feature              50000 non-null  str
 14  desired_future_feature          50000 non-null  str
 15  primary_device                  50000 non-null  str
 16  playlists_created               50000 non-null  int64
 17  avg_skips_per_day               50000 non-null  int64
dtypes: float64(1), int64(7), str(10)
memory usage: 6.9 MB

In [9]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

df["inactive_3_months_flag"] = df["inactive_3_months_flag"].astype(bool)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   user_id                         50000 non-null  int64
 1   country                         50000 non-null  str
 2   age                             50000 non-null  int64
 3   signup_date                     50000 non-null  datetime64[us]
 4   subscription_type               50000 non-null  str
 5   subscription_status             50000 non-null  str
 6   months_inactive                 50000 non-null  int64
 7   inactive_3_months_flag          50000 non-null  bool
 8   ad_interaction                  50000 non-null  str
 9   ad_conversion_to_subscription   50000 non-null  str
 10  music_suggestion_rating_1_to_5  50000 non-null  int64
 11  avg_listening_hours_per_week    50000 non-null  float64
 12  favorite_genre                  50000 non-null  str
 13  most_liked_feature              50000 non-null  str
 14  desired_future_feature          50000 non-null  str
 15  primary_device                  50000 non-null  str
 16  playlists_created               50000 non-null  int64
 17  avg_skips_per_day               50000 non-null  int64
dtypes: bool(1), datetime64[us](1), float64(1), int64(6), str(9)
memory usage: 6.5 MB

## Verificação de Duplicidade de Registros

Foi realizada a análise de duplicidade de registros com base na coluna `user_id`, utilizando o método `duplicated().sum()` para identificar a existência de possíveis entradas repetidas no dataset.

O resultado retornado foi 0, indicando que não foram identificados registros duplicados.

Dessa forma, conclui-se que a chave identificadora `user_id` possui unicidade garantida, assegurando a integridade dos registros e evitando impactos em métricas agregadas e análises estatísticas subsequentes.

In [36]:
df["user_id"].duplicated().sum()

np.int64(0)

## Análise de Consistência das Colunas Categóricas

Análise das colunas do tipo string com o objetivo de verificar a padronização dos valores categóricos e identificar possíveis inconsistências textuais, como diferenças de capitalização, grafia ou espaços indevidos.

Foram avaliadas as colunas `subscription_type`, `country`, `subscription_status`, `ad_interaction`, `ad_conversion_to_subscription`, `most_liked_feature`, `desired_future_feature` e `primary_device` utilizando o método `.value_counts()` para inspeção das categorias e suas respectivas frequências.

Não foram identificadas inconsistências de padronização, como variações do tipo `"Brazil"`, `"brazil"` ou `"brasil"`, indicando uniformidade nos valores categóricos do dataset.

A distribuição das frequências entre as categorias também se apresentou equilibrada, sem ocorrência de valores desproporcionais ou indícios de anomalias relevantes nas variáveis categóricas.

In [28]:
df["subscription_type"].value_counts()

subscription_type
Free                  22525
Premium Individual    14029
Student                4516
Premium Family         4482
Premium Duo            4448
Name: count, dtype: int64

In [29]:
df["country"].value_counts()

country
India        4265
Brazil       4215
Canada       4203
Mexico       4196
Indonesia    4172
Germany      4160
Spain        4149
UK           4147
Italy        4142
France       4137
Australia    4114
USA          4100
Name: count, dtype: int64

In [30]:
df["subscription_status"].value_counts()

subscription_status
Active      42109
Inactive     7891
Name: count, dtype: int64

In [31]:
df["ad_interaction"].value_counts()

ad_interaction
No     32514
Yes    17486
Name: count, dtype: int64

In [32]:
df["ad_conversion_to_subscription"].value_counts()

ad_conversion_to_subscription
No     45648
Yes     4352
Name: count, dtype: int64

In [38]:
df["favorite_genre"].value_counts()

favorite_genre
Classical     4272
Bollywood     4246
K-Pop         4228
Latin         4203
Indie         4182
Electronic    4144
Country       4135
Jazz          4134
Hip-Hop       4125
Rock          4120
R&B           4114
Pop           4097
Name: count, dtype: int64

In [33]:
df["most_liked_feature"].value_counts()

most_liked_feature
Lyrics             6358
Radio              6271
Offline Mode       6242
Discover Weekly    6240
Playlists          6238
Daily Mix          6236
Podcasts           6216
AI DJ              6199
Name: count, dtype: int64

In [34]:
df["desired_future_feature"].value_counts()

desired_future_feature
Mood-based Auto Playlists    8419
Concert Alerts               8403
Social Listening             8369
Better AI Recommendations    8335
Lyrics Translation           8243
HiFi Audio                   8231
Name: count, dtype: int64

In [35]:
df["primary_device"].value_counts()

primary_device
Smart Speaker    10050
Car System       10044
Desktop          10037
Mobile            9937
Tablet            9932
Name: count, dtype: int64

## Análise Estatística das Colunas Numéricas

Realização da análise estatística descritiva das colunas numéricas utilizando o método `describe()` com o objetivo de identificar padrões de distribuição, médias, valores mínimos e máximos, além de possíveis desvios ou inconsistências nos dados.

A análise demonstrou consistência nos valores numéricos do dataset, não sendo identificados registros fora do padrão ou anomalias relevantes nas variáveis avaliadas.

Entre os principais resultados observados:

- A média de idade dos usuários foi de aproximadamente 38 anos, com valores variando entre 16 e 60 anos;
- O tempo médio de inatividade foi de aproximadamente 1,5 meses, com valor máximo de 18 meses;
- A média de avaliação das sugestões musicais foi de 3,64 em uma escala de 1 a 5;
- A coluna de avaliação das sugestões musicais apresentou valores mínimos e máximos iguais a 1 e 5, respectivamente, indicando que todos os registros estavam dentro do intervalo válido de avaliação definido pelo dataset. Dessa forma, não foi necessária a realização de tratamentos corretivos ou remoção de registros inconsistentes.
- Os usuários apresentaram média de aproximadamente 10 horas semanais de consumo da plataforma;
- A média de playlists criadas foi de 8 por usuário;
- A média de músicas ignoradas por dia foi de aproximadamente 10.

A análise também permitiu verificar que os intervalos mínimos e máximos das variáveis se mantiveram coerentes em relação ao contexto do dataset, indicando boa consistência dos dados numéricos.

In [27]:
df.describe()

,user_id,age,signup_date,months_inactive,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,playlists_created,avg_skips_per_day
count,50000.000000,50000.000000,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,38.010280,2022-02-01 03:01:50.592000,1.533020,3.644100,9.988986,8.002680,10.025920
min,1.000000,16.000000,2018-01-01 00:00:00,0.000000,1.000000,0.000000,0.000000,1.000000
25%,12500.750000,27.000000,2020-01-19 00:00:00,0.000000,3.000000,7.280000,6.000000,8.000000
50%,25000.500000,38.000000,2022-01-31 00:00:00,1.000000,4.000000,9.980000,8.000000,10.000000
75%,37500.250000,49.000000,2024-02-16 00:00:00,2.000000,5.000000,12.680000,10.000000,12.000000
max,50000.000000,60.000000,2026-03-01 00:00:00,18.000000,5.000000,26.250000,23.000000,25.000000
std,14433.901067,12.984989,NaN,1.952082,1.114424,3.968927,2.831571,3.165579

## Exportação do Dataset Tratado

Após a realização das etapas de limpeza, validação e padronização dos dados, o dataset foi exportado para um novo arquivo CSV utilizando o método `to_csv()` da biblioteca Pandas.

O arquivo gerado foi salvo como `spotify_tratado.csv` e contém todas as transformações aplicadas durante o processo de ETL, incluindo ajustes de tipagem, tratamento de consistência e validação de integridade dos dados.

In [37]:
df.to_csv("../data/spotify_tratado.csv", index=False)